version: '3.8'

services:
  backend:
    build:
      context: ./docker/php
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    ports:
      - 8000:8000
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db

  frontend:
    image: node:18
    container_name: react_app
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

